### PR TITLE
replace "sklearn" dependency with "scikit-learn"

### PR DESCRIPTION
**Pull request by adriangb**
See https://pypi.org/project/sklearn/

### CODE REVIEW

**Review by thomasbird — APPROVED** [review]
Thanks for the MR!

**Comment by adriangb** [comment]
Please confirm but I don't think the CI failures are related to this change

**Comment by thomasbird** [comment]
Yeah seems super unlikely it was this MR, probably it's related to an update of libpostal. I'm investigating now.

**Comment by adriangb** [comment]
Hi, any updates?

**Comment by adriangb** [comment]
Can we move forward with this or close it @thomasbird ? Thanks

**Pull request closed without merging**
