### PR TITLE
Replace StopIteration with return (PEP 479)

### PR DESCRIPTION
**Pull request by roman-y-korolev**

### CODE REVIEW

**Comment by wdoug** [comment]
@deanmalmgren might we be able to get some of these PRs merged? This PR, in particular, is required for us to use this project in a python 3.7 environment.

**Comment by trorsty** [comment]
Bumping this - would be great to get this working in a Python 3.7 environment!

**Comment by petterill** [comment]
Indeed would be great if this could be merged. As a workaround, I installed a fork with this PR merged and it works nicely with Python 3.7.7.

**Comment by aCampello** [comment]
Is the support to this project decreasing? Seems that these PRs should be merged a long ago - it would be useful for me who am intending to use the package. Is there a fork or something?

**Comment by thomasbird** [comment]
Scrubadub has some new manpower. So let's get this merged. :)

**Comment by aCampello** [comment]
Awesome to see that this was fixed, and that the project is active again! Are you guys thinking about participating of Hacktoberfest? (https://hacktoberfest.digitalocean.com). I would be up for contributing to some of the issues, but would be good to know whether there are any priorities/roadmap for the project.

**Comment by thomasbird** [comment]
We hadn't planned in actively participating, but if you want help out, there's always things to do! My plan is for a slight tweak to the API that I'm working on at the moment, then to add some more detectors. I'll PM you and we can have this chat out of the pull request.

**Pull request merged**
